#!/bin/bash
echo btest.c
./../../rose/rose_build/bin/simpleMpiA btest.c
echo deadlock1.c
./../../rose/rose_build/bin/simpleMpiA deadlock1.c
echo deadlock2.c
./../../rose/rose_build/bin/simpleMpiA deadlock2.c
echo deadlock3.c
./../../rose/rose_build/bin/simpleMpiA deadlock3.c
echo deadlock4.c
./../../rose/rose_build/bin/simpleMpiA deadlock4.c
echo deadlock5.c
./../../rose/rose_build/bin/simpleMpiA deadlock5.c
echo deadlock6.c
./../../rose/rose_build/bin/simpleMpiA deadlock6.c
echo diffusion2.c
./../../rose/rose_build/bin/simpleMpiA diffusion2.c
echo diffusion2_nd.c
./../../rose/rose_build/bin/simpleMpiA diffusion2_nd.c
echo diffusion2_scaledown.c
./../../rose/rose_build/bin/simpleMpiA diffusion2_scaledown.c
echo diffusion.c
./../../rose/rose_build/bin/simpleMpiA diffusion.c
echo dtg.c
./../../rose/rose_build/bin/simpleMpiA dtg.c
echo GE.c
./../../rose/rose_build/bin/simpleMpiA GE.c
echo mat_mul.c
./../../rose/rose_build/bin/simpleMpiA mat_mul.c
echo monte.c
./../../rose/rose_build/bin/simpleMpiA monte.c
echo probe-unexp.c
./../../rose/rose_build/bin/simpleMpiA probe-unexp.c
echo steve-mat-mul.c
./../../rose/rose_build/bin/simpleMpiA steve-mat-mul.c
echo t1.c
./../../rose/rose_build/bin/simpleMpiA t1.c
echo test01.c
./../../rose/rose_build/bin/simpleMpiA test01.c
echo test02.c
./../../rose/rose_build/bin/simpleMpiA test02.c
echo test04.c
./../../rose/rose_build/bin/simpleMpiA test04.c
echo test1.c
./../../rose/rose_build/bin/simpleMpiA test1.c
echo test2.c
./../../rose/rose_build/bin/simpleMpiA test2.c
echo test3.c
./../../rose/rose_build/bin/simpleMpiA test3.c
echo test4.c
./../../rose/rose_build/bin/simpleMpiA test4.c
echo test5.c
./../../rose/rose_build/bin/simpleMpiA test5.c
echo test6.c
./../../rose/rose_build/bin/simpleMpiA test6.c
echo test7.c
./../../rose/rose_build/bin/simpleMpiA test7.c

